tap "homebrew/services"
tap "caskroom/cask"
tap "wata727/tflint"
tap "caskroom/fonts"

#CLI apps
brew "ack"
brew "fortune"
brew "cowsay"
brew "awscli"
brew "bat"
brew "git"
brew "git-extras"
brew "go"
brew "jq"
brew "jsonpp"
brew "neovim"
brew "nvm"
brew "python3"
brew "sqlite"
brew "terraform"
brew "tflint"
brew "wget"
brew "yarn"
brew "zsh"
brew "zsh-syntax-highlighting"
brew "bash-completion"
cask "dotnet-sdk"
brew "tree"
tap "eddieantonio/eddieantonio" #for Brewcat
brew "imgcat"
brew "exercism"
brew "lolcat"
brew "postgresql"

#Docker
cask "docker"
brew "docker-completion"
brew "docker-compose-completion"
brew "docker-machine-completion"

#GUI apps
cask "intellij-idea-ce"
cask "visual-studio-code"
cask "slack"
cask "google-chrome"
cask "firefox-nightly"
cask "tor-browser"
cask "spotify"
cask "iterm2"
cask "alfred"
cask "postman"

#Fonts
cask "font-inconsolata-dz"
cask "font-inconsolata-dz-for-powerline"
cask "font-fontawesome"
cask "font-awesome-terminal-fonts"
cask "font-hack"
cask "font-inconsolata-dz-for-powerline"
cask "font-inconsolata-g-for-powerline"
cask "font-inconsolata-for-powerline"
cask "font-roboto-mono"
cask "font-roboto-mono-for-powerline"
cask "font-source-code-pro"
cask "font-input"
